### ISSUE TITLE
selection returns string

### ISSUE THREAD

**Issue by thunderbug1** [domoritz/streamlit-vega-lite-demo#2]
This code seems to be broken and also the online demo gets some error (without any desciption)

When I run the code then the line:
`selection = altair_component(make_altair_scatterplot())`
returns a string instead of a dict.
This can be easily fixed with:

`selection_raw = altair_component(make_altair_scatterplot())`
`import json`
`selection = json.loads(selection_raw)`

however the numbers of _vgsid_ seem not to correlate with the iloc positions anymore and also change with every refresh.

**Comment by domoritz** [comment]
Hmm, sounds like streamlit changed something. Could you take a look at the change log and see whether there is something related?

**Comment by domoritz** [comment]
Looks like it's a regression in Streamlit: https://github.com/streamlit/streamlit/issues/3507
